# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Current Java LTS & minimum supported by Minecraft
        ]
        # and run on both Linux and Windows
        os: [ubuntu-20.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Fix code style violations
        run: ./gradlew spotlessApply --info --refresh-dependencies
      - name: Commit format changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: 自动修复代码格式'
          file_pattern: '*.java'
      - name: build
        run: |
          export GRADLE_OPTS="-Xmx4g -Dorg.gradle.daemon=false"
          ./gradlew build --stacktrace --info --refresh-dependencies --continue
        env:
          MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3
          GRADLE_OPTS: "-Dorg.gradle.parallel=true -Dorg.gradle.caching=true"
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
