# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # 使用Java 21
        java: [21]
        # 在Linux和Windows上运行
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 验证Gradle包装器
        uses: gradle/wrapper-validation-action@v1
      - name: 设置JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: 设置Gradle包装器权限
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: 构建
        run: ./gradlew build
      - name: 上传构建产物
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
